### ISSUE TITLE
Text strings must be rendered within a <Text> component

### ISSUE THREAD

**Issue by kings2000** [jobtoday/react-native-image-viewing#66] opened 2020-08-11 20:30 UTC
This error is located at:
    in RCTView (at View.js:34)
    in View (at SafeAreaView.js:41)
    in ForwardRef(SafeAreaView) (at App.js:35)
    in App (at renderApplication.js:45)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:106)
    in RCTView (at View.js:34)
    in View (at AppContainer.js:132)
    in AppContainer (at renderApplication.js:39)
[Tue Aug 11 2020 21:27:52.462]  ERROR    Error: Text strings must be rendered within a <Text> component.

**Comment by jzyds** [comment] 2020-09-07 10:23
Same error

**Comment by jzyds** [comment] 2020-09-09 02:56
I find out what the problem is, an ";" after the sample code

```
<ImageView
  images={images}
  imageIndex={0}
  visible={visible}
  onRequestClose={() => setIsVisible(false)}
/>;
```

**Comment by jzyds** [comment] 2020-09-09 02:58
```
<ImageView
  images={images}
  imageIndex={0}
  visible={visible}
  onRequestClose={() => setIsVisible(false)}
/>;
```

Remove the semicolon at the end of the sample code

**Comment by pavelbrylov** [comment] 2020-09-21 17:21
Fixed in https://github.com/jobtoday/react-native-image-viewing/pull/69

**Closed by pavelbrylov** 2020-09-21 17:21 UTC
