### ISSUE TITLE
Android: modal is not covering all the screen

### ISSUE THREAD

**Issue by nicoferreyra** [jobtoday/react-native-image-viewing#12] opened 2020-01-14 21:16 UTC
Hey guys! I'm facing an issue on Android where the modal with the image is not covering all the screen and it's only showing a small part of the image. On iOS is working very well 👍 

react: 16.8.3
react-native: 0.61.5
react-native-image-viewing: 0.1.3

Another useful information is that I'm using Expo SDK v35.0.0.

Can you please tell me what can I do to fix this? 

Thank you!

**Comment by antonKalinin** [comment] 2020-01-16 10:50
Hey @nicoferreyra, could you please check is the same bug exists in expo example app on your device? https://exp.host/@antonkalinin/react-native-image-viewing

- If it does represent: then could you please specify what android device do you use?
- If it doesn't represent: then it's probably because of the way you use `ImageVIew` in your screen. Because of some bugs in React Native default modal we had to write own implementation of modal and it's just an absolute positioned `View`, so if the container of the `ImageView` is small, then the `ImageView` itself will be also small. The solution in this case is to put `ImageView` out of containers somewhere closer to the root view.

**Comment by zhitomir-oreshenski-mm** [comment] 2020-02-12 15:08
Hello,

I am facing the same issue, and I see that you are adding additional style(top: StatusBar.currentHeight) into Modal.android.js.

The issue can be found for following devices: Pixel 3, Nexus 5X. If I attempt to remove the top style it is working well.
![Screenshot 2020-02-12 at 17 07 41](https://user-images.githubusercontent.com/58042315/74347763-3cf27580-4dba-11ea-841c-3d8140d5945e.png)


Best regards,
Zhitomir

**Comment by uokesita** [comment] 2020-02-12 16:05
@zhitomir-oreshenski-mm The problem is that now the close button in on the very top https://share.getcloudapp.com/v1ur1lpL

**Comment by zhitomir-oreshenski-mm** [comment] 2020-02-12 16:12
@uokesita It seems that StatusBar.currentHeight doesn't calculate properly the height of the screen, it doubles the height of Android OS header.
![Screenshot 2020-02-12 at 17 07 41](https://user-images.githubusercontent.com/58042315/74353824-243a8d80-4dc3-11ea-933a-0480948804a3.png)

**Comment by zhitomir-oreshenski-mm** [comment] 2020-02-12 17:31
Hi,

I've made a PR for adding dynamic style props to ImageView container

BR,
Zhitomir

**Comment by ManigandanRaamanathan** [comment] 2020-02-15 15:12
@zhitomir-oreshenski-mm i face similar issue but the gap is huge 
![image](https://user-images.githubusercontent.com/22089729/74590350-91128980-5048-11ea-8caf-18510c15e5b6.png)

**Comment by ManigandanRaamanathan** [comment] 2020-02-15 15:17
@zhitomir-oreshenski-mm i suspect that it is not recognising whether the statusbar visible or not

**Comment by ManigandanRaamanathan** [comment] 2020-02-15 15:21
@zhitomir-oreshenski-mm @antonKalinin @nicoferreyra the issue is here. Commenting this line will fix the model height perfectly.
![image](https://user-images.githubusercontent.com/22089729/74590493-ddaa9480-5049-11ea-8933-5b853868a7da.png)

**Comment by ManigandanRaamanathan** [comment] 2020-02-15 16:08
Pulled a merge request #22 . Feel free to modify and merge. Thanks for the wonderful library.

**Comment by zhitomir-oreshenski-mm** [comment] 2020-02-19 07:38
Hi @ManigandanRaamanathan,

Yes, the issue can be seen only on specific screens. By adding dynamic style you can add or remove additional Statusbar height based on particular OS (with or without notch).

Hope that soon it can be tested so that we will have this fix.

Best regards,
Zhitomir

**Comment by TylerPin** [comment] 2020-02-20 04:02
Quick fix is by manually wrapping it inside a modal and provide a black background over it
`    <Modal isVisible={this.state.isImageViewerVisible} onBackButtonPress={this.imageViewerDismiss} style={{ margin: 0 }}>
          <View style={{ flex:1, backgroundColor: 'black' }}>
            <ImageView
              images={images}
              imageIndex={0}
              visible={this.state.isImageViewerVisible}
              onRequestClose={this.imageViewerDismiss}
            />
          </View>
        </Modal>`

**Comment by ZChenzy** [comment] 2020-02-27 18:42
@TylerPin 
The pinch to zoom doesn't work after it is put in the Modal. Does it work for you?

**Comment by zhitomir-oreshenski-mm** [comment] 2020-02-29 17:43
Hello,

Would you be so kind to review both PR and merge some of them in order to solve the issue?

The situation is a bit urgent now.

Thanks in advance.

**Comment by antonKalinin** [comment] 2020-03-02 21:00
@nicoferreyra @zhitomir-oreshenski-mm @ManigandanRaamanathan @TylerPin We've merged fix to master and going to release new version tomorrow morning after couple of tests. Could you please approve from your side that the version in master fixes your issue?

**Comment by loustak** [comment] 2020-03-03 14:47
> @nicoferreyra @zhitomir-oreshenski-mm @ManigandanRaamanathan @TylerPin We've merged fix to master and going to release new version tomorrow morning after couple of tests. Could you please approve from your side that the version in master fixes your issue?
> 
> To hide status bar:
> 
> ```js-jsx
> <ImageViewing
>   ...
>   presentationStyle="overFullScreen"
> />;
> ```

When I try to test on my project using `npm install git+ssh://git@github.com:jobtoday/react-native-image-viewing.git`  only the LICENSE, README.md and package.json files are downloaded inside the node_modules of this package. 

And of course when I try to use the package it crash with the following message:

`
error: bundling failed: Error: While trying to resolve module `react-native-image-viewing` from file `front/src/pages/ProfileComponent.js`, the package `front/node_modules/react-native-image-viewing/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`front/node_modules/react-native-image-viewing/dist/index.js`. Indeed, none of these files exist:

  * front/node_modules/react-native-image-viewing/dist/index.js(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * front/node_modules/react-native-image-viewing/dist/index.js/index(.native|.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at ResolutionRequest.resolveDependency (/mnt/hdd/dev/cupido-front/front/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)

`

What is happening?

**Comment by antonKalinin** [comment] 2020-03-03 14:55
@loustak Yeah, there is not build directory on github, so the only way to test is to clone repo and build it,  I guess. But anyway I think we are ready for new version. So going to publish it in an hour.

**Comment by loustak** [comment] 2020-03-03 14:57
@antonKalinin yep found my mistake when I saw the `dist/index.js` in package.js. Anyway I'll test it as soon as published since my project need it. Thanks a lot :)

**Comment by antonKalinin** [comment] 2020-03-03 19:17
v0.1.7 is released so please check that everything is fine by passing next prop:

```jsx
<ImageViewing
  ...
  presentationStyle="overFullScreen"
/>;
```

Closing this issue, feel free to reopen if something is wrong.

**Closed by antonKalinin** 2020-03-03 19:17 UTC

**Comment by nicoferreyra** [comment] 2020-03-03 19:48
Thank you very much @antonKalinin  !!

**Comment by TylerPin** [comment] 2020-03-04 01:42
Tested good on my Android HTC Desire 12, version 7.1.1.

Appreciate the hard work you put in!

**Comment by antonKalinin** [comment] 2020-03-04 11:20
Big thanks to @maksimko for PR with fix for the issue!

**Comment by hudiohizari** [comment] 2020-03-06 06:49
@antonKalinin I found another bugs (or am i do it wrong?), i used
```
<Card>
   <ImageViewing
     ...
    presentationStyle="overFullScreen"
   />
</Card>
```

but it only fills it's parent not entire screen

**Comment by barbarossusuz** [comment] 2020-03-08 16:18
@hudiohizari I had the same problem, I hide the status bar when the imageViewModal is open that fixed my problem.

**Comment by fukemy** [comment] 2022-06-07 14:00
presentationStyle="overFullScreen" not working to me

**Comment by janpe** [comment] 2022-09-14 05:20
Could this be reopened? On Android 10 `overFullScreen` doesn't work.

**Comment by janpe** [comment] 2022-09-14 05:47
@antonKalinin there seems to still be problems with this as the issue #161 and the comment above suggests.

**Comment by fukemy** [comment] 2022-09-15 05:17
I ended up to using native module to write own lightbox. Its better performance and ux

**Comment by appsgenie** [comment] 2022-09-23 23:36
I think exposing the `statusBarTranslucent` property can also help here with Android status bars...
